- hosts: stagingserver
  user: jenkins
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars: 
    copy_dest: "{{ artificat }}"
  tasks:
  - name: Copy Code to StagingServer
    copy:
      src: "{{ copy_dest }}"
      dest: /tmp
